### ISSUE TITLE
Update iambaim/pyEcholab to fix NaN values in last ping

### ISSUE THREAD

**Issue by ingeke** [CRIMAC-WP4-Machine-learning/CRIMAC-preprocessing#10]
Update https://github.com/iambaim/pyEcholab to get latest fixes from https://github.com/CI-CMG/pyEcholab.

An indentation error that caused sv values in the last ping to be NaN has been fixed:
https://github.com/CI-CMG/pyEcholab/commit/5d39ea6474ec5441da209059e19d88591a6239f1#diff-2ca64f9ab4b4f647b00b574e64be6b4fd318f221cd013604d144ac6921b0e9adR3366

**Comment by iambaim** [comment]
This is done. The image will be ready soon. Thanks.
