### ISSUE TITLE
Annotations in preprocessed data

### ISSUE THREAD

**Issue by nilsolav** [CRIMAC-WP4-Machine-learning/CRIMAC-preprocessing#2]
The annotations needs to be included in the .zarr or .nc files. Since we are using a gridded data set, i.e. the time-range grid is similar between channels, a "pixelbased" representation should work. The labels will then be tied to the data grid, but I think that is ok for this level of processing.

For IMR data, the label information is stored in the .work files, and code to parse these files are being developed here: https://github.com/CRIMAC-WP4-Machine-learning/CRIMAC-annotationtools 

My suggestion is to write a gridded format on this form L[time,range,category]="proportion of pixel to a category". Compression needs to be used to avoid storing lots of zeroes for pixels not allocated to a class, or in cases where a fixed proportion over a large region is allocated to a class. The "category" vector should use the ICES categories, in addition to other categories like different noise types etc.

**Comment by nilsolav** [comment]
LSSS also differentiate between schools and regions, and the convention suggests a layer order when converting to pixel based masks. The idea is that school boxes "overrides" the regions.

**Comment by sindrevatnehol** [comment]
Actually it is possible to have 3 "layer" overlapping, the layer itselfe, the school, and erased pixels. School boxes overrides the layer/regions, the erased pixels overrides both schools and regions. It is possible to represent them all pixelbased but have different  priority on the pixels. I.E. 1 is highest priority (erased), 2 is medium priority (school) and 3 is low priority (layer).

**Comment by iambaim** [comment]
@nilsolav  I think this is the most straightforward way if we want to store the annotations inside the same file. However, we need to do some further experiments regarding:

1. **Computational complexity**. To get even a pixel of a simple shape, we might need to loop through all the category axis. Now, this works fine if we don't have many categories. However, higher number of category will likely to have effect on the processing time.

2. **Store (+append) capability**. Right now we can't have two unlimited axis when appending into an existing data (zarr/nc) files. Therefore, adding a layer/category will require us to load/process the whole layer and append it into an existing file. Editing is fine though. Pre-allocation with a zero mask can be a solution. But, what about point number 1 above?

**Comment by nilsolav** [comment]
we have changed the approach to use zarr files for the annotations instead of the parquet files. The code needs to be updated to do this.

**Comment by nilsolav** [comment]
The preprocessor now stores the annotations in zarr format. Well done everyone!
