### ISSUE TITLE
Error for EK80 data with power/angle

### ISSUE THREAD

**Issue by ingeke** [CRIMAC-WP4-Machine-learning/CRIMAC-preprocessing#7]
The error `AttributeError("'raw_data' object has no attribute 'pulse_length'")` occurs on the line

https://github.com/CRIMAC-WP4-Machine-learning/CRIMAC-preprocessing/blob/f2d624344d3641481ca2fea89f54ccfa3267d9be/CRIMAC_preprocess.py#L208

when processing for example cruise_data/2020/S2020821_PEROS_3317/ACOUSTIC/EK80/EK80_RAWDATA/2020821-D20200425-T170830.raw.

It seems that [pyEcholab](https://github.com/CI-CMG/pyEcholab) uses `pulse_length` for EK60 and `pulse_duration` for EK80. It would have been better if they used `pulse_duration` for both.

**Comment by iambaim** [comment]
Thank you! This is fixed in https://github.com/CRIMAC-WP4-Machine-learning/CRIMAC-preprocessing/commit/bfb19df383c10933deeeb839b6c7273375491800 .
