### ISSUE TITLE
Processing stops on corrupt raw files

### ISSUE THREAD

**Issue by ingeke** [CRIMAC-WP4-Machine-learning/CRIMAC-preprocessing#9]
The error `AttributeError("'NoneType' object has no attribute 'raw_data'` happens on the line

https://github.com/CRIMAC-WP4-Machine-learning/CRIMAC-preprocessing/blob/a8bc60d9981e6703c7d9fce93be80ac65a9e5f99/CRIMAC_preprocess.py#L393

cruise_data\2020\S2020819_PVENDLA_3206\ACOUSTIC\EK60\EK60_RAWDATA\2020819-D20200222-T213824.raw.

This raw file is corrupt, causing ek_read to return `None`, leading to the error above.

While the file is corrupt and cannot be processed, the processing could still continue with the next file.

**Comment by iambaim** [comment]
Thanks, @ingeke !
This is fixed in the latest push. Please check.
